name: pandas_skyfield_extension
dependencies:
  - astropy
  - ipykernel
  # - pandas>=3.1.0
  - geopandas
  - pip
  - pytest
  - pytest-cov
  - skyfield
  - pip:
    - git+https://github.com/pandas-dev/pandas.git
    - git+https://github.com/Julian-Harbeck/pandas-units-extension.git@dev
    - git+https://github.com/Julian-Harbeck/pandas-skyfield-extension.git
