[project]
name = "pandas-skyfield-extension"
version = "0.1.0"
description = "Pandas Extension for Skyfield"
readme = "README.md"
authors = [
    { name = "Julian Harbeck" }
]
requires-python = ">=3.11"
dependencies = [
    "astropy",
    "pandas>=3.0.1",
    "skyfield",
#    "pandas-units-extension>=0.2.0"
]

[project.optional-dependencies]
geo = ["geopandas[all]"]
